# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Semtech LoRa SX1278 drivers
# 

# Compiler can find the header in the current directory.
ccflags-y += -I$(src)  

obj-$(CONFIG_LORA_SX1278) += sx1278.o